version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./recentMessages.json:/app/recentMessages.json
    env_file:
      - ./.env
